name: Build and Test

on: [push]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install Dependencies
        run: |
          npm install
          cd ios && pod install && cd ..

      - name: Build iOS
        run: |
          xcodebuild -workspace ios/HappyHomeUI.xcworkspace -scheme HappyHomeUI -sdk iphonesimulator -arch x86_64

      - name: Build Android
        run: |
          cd android && ./gradlew assembleDebug
